@id=AAD3B2FB-C5CE-45CF-A52A-7D3F8A4ADDEF
GET http://localhost:5175/roles/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTI4NTM3Ni0xZDkyLTRkNGYtOTFlZS1jYTNiYThkYzY1MDAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJqdGkiOiJjODIxYjJhZi0yMzE4LTQwMGQtYjM0MS1jYzNlNTFmZjY0OGYiLCJleHAiOjE3MjY2NzM2MTYsImlzcyI6Imh0dHBzOi8vaXNzdWVyLmNvbSIsImF1ZCI6Imh0dHBzOi8vYXVkaWVuY2UuY29tIn0.TN99Diw_gMOyRnueWsfH9oMwQ_B9QfF22dsuXp1wLyU