@id=FFED4082-FAA6-4763-BF18-498555BE46CB

PUT http://localhost:5175/tasks/{{id}}
Content-Type: application/json

{
    "title": "Tarea de El otro 1",
    "description": "Se realizó una modificación de esta tarea",
    "status": 1,
    "assignedTo": "04ECA5DD-A69B-4867-9F5D-5AAB3197395D"
}