POST http://localhost:5175/users
Content-Type: application/json

{
    "name": "Me van a borrar",
    "email": "borrado@gmail.com",
    "passwordHash": "adios123",
    "roleId": "9F6025DA-6072-41DD-B335-3E4CD4109534"
}