POST http://localhost:5175/users
Content-Type: application/json

{
    "name": "Ana De Armas",
    "email": "anadearmas@gmail.com",
    "passwordHash": "anadearmas123",
    "roleId": "05DF3BF5-873F-41A6-82C7-942B427EA502"
}