@id=064CDC3B-3540-40A3-8D84-B308D0BEC3CA

DELETE http://localhost:5175/users/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YjAzMmEwNS1kNDkyLTQ4ZjgtYWViMS01ZTY4YjMwMGY3MjkiLCJlbWFpbCI6InBydWViYTIyMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFbXBsZWFkbyIsImp0aSI6IjM4MWIyYzcwLTY1ZjctNGM3Ni1hNTZkLTc1NTVkZmMyNTExOCIsImV4cCI6MTcyNjQ4MjAxNCwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuY29tIiwiYXVkIjoiaHR0cHM6Ly9hdWRpZW5jZS5jb20ifQ.qX-rRhBcH5qsKgqWEA2x32reYpYTCxtKNVCWixKpbFk