GET http://localhost:5175/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTI4NTM3Ni0xZDkyLTRkNGYtOTFlZS1jYTNiYThkYzY1MDAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJqdGkiOiI2MDVmYWFlMS0yNjlmLTRjZmYtYTY2ZC1hN2Q1YjllZjE4M2UiLCJleHAiOjE3MjY2NzYwNzQsImlzcyI6Imh0dHBzOi8vaXNzdWVyLmNvbSIsImF1ZCI6Imh0dHBzOi8vYXVkaWVuY2UuY29tIn0.UuAywyMnGa6nBvPoeGUiyPHXx5tnvjxVmpxezSy04Lk