@id=04ECA5DD-A69B-4867-9F5D-5AAB3197

PUT http://localhost:5175/users/{{id}}
Content-Type: application/json

{
    "name": "Mi usuario modificado",
    "email": "correocambiado@gmail.com",
    "passwordHash": "hola123",
    "roleId": "05DF3BF5-873F-41A6-82C7-942B427EA502"
}